account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="account/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('sign/', views.sign, name='sign'),
    path('<user_id>/', views.user, name='user'),
    path('<user_id>/edit', views.user_edit, name='user_edit'),

    path('<user_id>/follow/', views.follow, name='follow'),
    path('<user_id>/unfollow/', views.unfollow, name='unfollow'),
    path('<user_id>/follow_list', views.follow_list, name='follow_list'),

    path('<user_id>/review/new/', views.review_new, name='review_new'),
    path('<user_id>/review/<int:review_id>/edit/',
         views.review_edit, name='review_edit'),
    path('<user_id>/review/<int:review_id>/delete/',
         views.review_delete, name='review_delete'),
]

concertmeet/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('meetapp.urls')),
    path('user/', include('account.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meetapp/urls.py
from django.urls import path
from . import views

app_name = 'meetapp'

urlpatterns = [
    path('', views.post_home, name='post_home'),
    path('search', views.search_result, name='search_result'),
    path('lists/', views.post_list, name='post_list'),
    path('like/', views.post_like, name='post_like'), 
    path('lists/<int:post_id>/', views.post_detail, name='post_detail'),
    path('lists/new/', views.post_new, name='post_new'),
    path('lists/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('lists/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path('lists/<int:post_id>/declaration/', views.post_declaration, name='post_declaration'),
    path('lists/<int:post_id>/comment/<int:comment_id>/declaration/', views.comment_declaration, name='comment_declaration'),
    path('lists/<int:post_id>/comment/new/', views.comment_new, name='comment_new'),
    path('lists/<int:post_id>/comment/<int:id>/edit/', views.comment_edit, name='comment_edit'),
    path('lists/<int:post_id>/comment/<int:id>/delete/', views.comment_delete, name='comment_delete'),
    path('lists/<int:post_id>/comment/<int:comment_id>/pcpadd', views.pcp_add, name='pcp_add'),
    path('lists/<int:post_id>/comment/<int:comment_id>/pcpdelete', views.pcp_delete, name='pcp_delete'),
    path('content/', views.content_list, name='content_list'),
]

meetapp/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from account.models import *


class Post(models.Model):
    category = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    user = models.ForeignKey('account.UserInfo', on_delete=models.CASCADE,)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    content = models.TextField()
    hit = models.IntegerField(default=-1)
    likes_user = models.ManyToManyField(
        'account.UserInfo', blank=True, related_name='likes_user')
    pcp = models.ForeignKey('Participant', on_delete=models.CASCADE)

    class Meta:
        ordering = ['-id']

    def count_likes_user(self):
        return self.likes_user.count()

    def __str__(self):
        return f'{self.title}'


class Participant(models.Model):
    created_user = models.ForeignKey(
        'account.UserInfo', on_delete=models.CASCADE,)
    # 공연 참가 유저수. 사용자가 존재하면 글 삭제 불가능. 유저 아이디 넣기
    pcp_user = models.ManyToManyField(
        'account.UserInfo', blank=True, related_name='pcp_user')

    pcp_user_count = models.IntegerField(default=1)
    pcp_user_total = models.IntegerField(default=4)

    def __str__(self):
        return f'{self.id}'


class Comment(models.Model):
    user = models.ForeignKey('account.UserInfo', on_delete=models.CASCADE,)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-id']

    def get_edit_url(self):
        return reverse('meetapp:comment_edit', args=[self.post.id, self.id])

    def get_delete_url(self):
        return reverse('meetapp:comment_delete', args=[self.post.id, self.id])


class PostDeclaration(models.Model):
    user = models.ForeignKey('account.UserInfo', on_delete=models.CASCADE,)
    message = models.TextField()
    post = models.ForeignKey(
        'Post', on_delete=models.CASCADE, null=True, blank=True)
    process = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.message}'


class CommentDeclaration(models.Model):
    user = models.ForeignKey('account.UserInfo', on_delete=models.CASCADE,)
    message = models.TextField()
    post = models.ForeignKey(
        'Post', on_delete=models.CASCADE, null=True, blank=True)
    comment = models.ForeignKey(
        'Comment', on_delete=models.CASCADE, null=True, blank=True)
    process = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.message}'


class Concert(models.Model):
    title = models.CharField(max_length=100)
    image_url = models.URLField('url', unique=True)
    location = models.CharField(max_length=100)
    date = models.CharField(max_length=100)
    genre = models.CharField(max_length=50)
    link = models.URLField('url', unique=True)

    def __str__(self):
        return f'{self.title}'

# class Photo(models.Model):
#     post = models.ForeignKey(Concert, on_delete=models.CASCADE, null=True)

meetapp/forms.py
from django import forms
from .models import *

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('category', 'title','content')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('message',)

class PostDeclareForm(forms.ModelForm):
    class Meta:
        model = PostDeclaration
        fields = ('message',)

class CommentDeclareForm(forms.ModelForm):
    class Meta:
        model = CommentDeclaration
        fields = ('message',)

meetapp/views.py
import json
from django.contrib.auth.decorators import login_required
from django.core import paginator
from django.core.paginator import EmptyPage, Paginator
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.views.decorators.http import require_POST
from django.shortcuts import get_object_or_404, render, redirect
from django.db.models import Q
from .forms import *
from .models import Post, Comment, PostDeclaration, CommentDeclaration


def post_home(request):
    hit_posts = Post.objects.all().order_by('-hit')[:10]
    concert_list = Concert.objects.all()
    context = {
        'posts': hit_posts,
        'concert_list': concert_list,
    }
    return render(request, 'meetapp/post_home.html', context)


def search_result(request):
    page = request.GET.get("page", 1)
    keyword = request.GET.get('keyword')
    results = Post.objects.filter(
        Q(title__icontains=keyword) | Q(content__icontains=keyword))
    paginator = Paginator(results, 10, orphans=3)
    try:
        lists = paginator.page(int(page))
    except EmptyPage:
        return redirect("/")
    context = {
        'searchstr': keyword,
        'posts': results,
        'page': lists,
    }
    return render(request, 'meetapp/search_result.html', context)


def post_list(request):
    page = request.GET.get("page", 1)
    post_list = Post.objects.all()
    paginator = Paginator(post_list, 10, orphans=3)
    try:
        lists = paginator.page(int(page))
        return render(request, "meetapp/post_list.html", {
            "page": lists
        })
    except EmptyPage:
        return redirect("/")


@login_required
@require_POST
def post_like(request):
    pk = request.POST.get('pk', None)
    post = get_object_or_404(Post, pk=pk)
    user = UserInfo.objects.get(userkey=request.user)

    if post.likes_user.filter(id=user.id).exists():
        post.likes_user.remove(user)
    else:
        post.likes_user.add(user)

    context = {'likes_count': post.count_likes_user()}
    return HttpResponse(json.dumps(context), content_type="application/json")


def post_detail(request, post_id):
    post = Post.objects.get(id=post_id)
    post.hit += 1
    post.save()
    form = CommentForm()
    if post.pcp.pcp_user.filter(id=request.user.id).exists():
        is_pcp = 1
    else:
        is_pcp = 0

    context = {
        'post': post,
        'form': form,
        'is_pcp': is_pcp,
    }
    return render(request, 'meetapp/post_detail.html', context)


def post_resethit(request, post_id):
    post = Post.objects.get(id=post_id)
    post.views = 0
    post.save()
    return render(request, 'meetapp/post_detail.html')


def post_new(request):
    if request.method == 'GET':
        form = PostForm()

    elif request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = UserInfo.objects.get(userkey=request.user)
            pcp = Participant.objects.create(created_user=post.user)
            try:
                max_pcp = request.POST.get('max_pcp')
                pcp.pcp_user_total = max_pcp
            except:
                pass
            pcp.save()
            post.pcp = pcp
            post.save()
            return redirect('meetapp:post_detail', post_id=post.id)

    return render(request, 'meetapp/post_new.html', {
        'form': form,
    })


def post_edit(request, post_id):
    post = Post.objects.get(id=post_id)

    if request.method == 'GET':
        form = PostForm(instance=post)

    elif request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post.hit -= 1
            try:
                max_pcp = request.POST.get('max_pcp')
                post.pcp.pcp_user_total = max_pcp
                post.pcp.save()
            except:
                pass
            post = form.save()
            return redirect('meetapp:post_detail', post_id=post.id)

    return render(request, 'meetapp/post_edit.html', {
        'form': form,
        'post': post,
    })


def post_delete(request, post_id):
    post = Post.objects.get(id=post_id)
    post.pcp.delete()
    post.delete()
    return redirect('meetapp:post_list')


@login_required
def post_declaration(request, post_id):
    post = Post.objects.get(id=post_id)

    if request.method == 'GET':
        form = PostDeclareForm()

    elif request.method == 'POST':
        form = PostDeclareForm(request.POST)
        if form.is_valid():
            declaration = form.save(commit=False)
            declaration.user = post.user
            declaration.post = post
            declaration.save()
            postdeclaration = form.save(commit=False)
            postdeclaration.user = post.user
            postdeclaration.post = post
            postdeclaration.save()
            return redirect('meetapp:post_detail', post_id=post.id)
    return render(request, 'meetapp/post_declaration.html', {
        'form': form,
    })


@login_required
def comment_declaration(request, post_id, comment_id):
    post = Post.objects.get(id=post_id)
    comment = Comment.objects.get(id=comment_id)
    if request.method == 'GET':
        form = CommentDeclareForm()

    elif request.method == 'POST':
        form = CommentDeclareForm(request.POST)
        if form.is_valid():
            commentdeclaration = form.save(commit=False)
            commentdeclaration.user = comment.user
            commentdeclaration.post = post
            commentdeclaration.comment = comment
            commentdeclaration.save()
            return redirect('meetapp:post_detail', post_id=post.id)

    return render(request, 'meetapp/comment_declaration.html', {
        'form': form,
    })


@login_required
def comment_new(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST, request.FILES)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.user = UserInfo.objects.get(userkey=request.user)
            comment.save()
            return redirect('meetapp:post_detail', post.id)
    return redirect('meetapp:post_detail', post.id)


@login_required
def comment_edit(request, post_id, id):
    comment = get_object_or_404(Comment, id=id)
    if comment.user.username != request.user.username:
        return redirect('meetapp:post_detail', post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST, request.FILES, instance=comment)
        if form.is_valid():
            comment = form.save()
            comment.save()
            return redirect('meetapp:post_detail', post_id)
    else:
        form = CommentForm(instance=comment)

    return render(request, 'meetapp/comment_form.html', {
        'form': form,
    })


@login_required
def comment_delete(request, post_id, id):
    comment = get_object_or_404(Comment, id=id)
    if comment.user.username != request.user.username:
        return redirect('meetapp:post_detail', post_id)
    comment.delete()
    return redirect('meetapp:post_detail', post_id)


def pcp_add(request, post_id, comment_id):
    post = get_object_or_404(Post, id=post_id)
    comment = get_object_or_404(Comment, id=comment_id)
    if post.pcp.pcp_user.filter(id=comment.user.userkey.id).exists():
        context = {'status': 0}
    else:
        post.pcp.pcp_user.add(comment.user)
        post.pcp.pcp_user_count += 1
        post.pcp.save()
        post.save()
        add_user = UserInfo.objects.get(username=comment.user.username)
        print(add_user.concertnum)
        add_user.concertnum += 1
        add_user.save()
        context = {'status': 1, 'pcp_user_count': post.pcp.pcp_user_count}

    return HttpResponse(json.dumps(context), content_type="application/json")


def pcp_delete(request, post_id, comment_id):
    post = get_object_or_404(Post, id=post_id)
    comment = get_object_or_404(Comment, id=comment_id)
    if post.pcp.pcp_user.filter(id=comment.user.userkey.id).exists():
        post.pcp.pcp_user.remove(comment.user)
        post.pcp.pcp_user_count -= 1
        post.pcp.save()
        post.save()
        del_user = UserInfo.objects.get(username=comment.user.username)
        del_user.concertnum -= 1
        if del_user.concertnum < 0:
            del_user.concertnum = 0
        del_user.save()
        context = {'status': 1, 'pcp_user_count': post.pcp.pcp_user_count}
    else:
        context = {'status': 0}

    return HttpResponse(json.dumps(context), content_type="application/json")


def content_list(request):
    concert_list = Concert.objects.all()
    context = {
        'concert_list': concert_list,
    }
    return render(request, 'meetapp/content_list.html', context)

meetapp/templates/meetapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <!-- fontawesome -->
  <script src="https://use.fontawesome.com/releases/v5.2.0/js/all.js"></script>

  <!-- Bootstrap -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous" />

  <!-- fonts -->
  <link rel="preconnect" href="https://fonts.gstatic.com" />
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100&display=swap" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons|Material+Icons+Outlined" rel="stylesheet" />

  <!-- jquery -->
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>


  <link rel="stylesheet" href="{% static 'css/reset.css' %}" />
  <link rel="stylesheet" href="{% static 'css/base.css' %}" />
  <link rel="stylesheet" href="{% static 'css/ui.css' %}" />

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8"
    crossorigin="anonymous"></script>
</head>

<body>
  <header class="header">
    <a href="{% url 'meetapp:post_home' %}">ConcertMeet</a>
    <form class="search-form" action="{% url 'meetapp:search_result' %}">
      <input type="search" style="box-shadow: 0 3px 10px rgb(0 0 0 / 0.1);" id="keyword" name="keyword"
        placeholder="검색하기" style="padding-left: 5%;">
      <button type="submit"><i class="fas fa-search"></i></button>
    </form>
    <div class="top_right" style="justify-content: center;">
      {% if user.is_authenticated %}
      <div>
        <a aria-current="page" id="logout" onclick="logout();" href="{% url 'account:logout' %}"
          >로그아웃</a>
      </div>
      <div>
        <a href="{% url 'account:user' user.username %}">마이페이지</a>
      </div>
      {% else %}
      <div>
        <a href="{% url 'account:login' %}">로그인</a>
      </div>
      <div>
        <a href="{% url 'account:sign' %}">회원가입</a>
        </li>
        {% endif %}
        </ul>
      </div>

  </header>
  <ul class="menu">
    <li class="menu-item"><a href="{% url 'meetapp:post_home' %}" class="menu-link">메인</a></li>
    <li class="menu-item"><a href="{% url 'meetapp:content_list' %}" class="menu-link">공연</a>
    </li>
    <li class="menu-item"><a href="{% url 'meetapp:post_list' %}" class="menu-link">커뮤니티</a>
    </li>
    <li class="menu-item"><a href="http://ticket.interpark.com/" class="menu-link" target='_blank'>예매</a></li>
  </ul>

  <div class="quickmenu">
    <ul>
      <li><a href="#" class="go-to-top">top</a></li>
      <li><a href="#" class="go-to-down">down</a></li>
    </ul>
  </div>


  {% block content %} {% endblock content %}

  <div class="df">
    <div class="copyright">© 2021 ConcertMeet. All rights reserved.</div>
  </div>

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
    integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
    integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
    crossorigin="anonymous"></script>

  <script>
    function logout() {
      alert("로그아웃 되었습니다!");
    }
  </script>
  <!-- <script src="{% static 'js/clock.js' %}"></script> -->
  <script>$(document).ready(function () {
      var currentPosition = parseInt($(".quickmenu").css("top"));
      var floatTarget = $("a.go-to-top");
      var Target = $("a.go-to-down");

      $(window).scroll(function () {
        var position = $(window).scrollTop();
        $(".quickmenu").stop().animate({ "top": position + currentPosition + "px" }, 1000);
      });

      floatTarget.click(function () {
        $("html, body").animate({ scrollTop: 0 }, 100);
        return false;
      });

      Target.click(function () {
        $('html, body').animate({ scrollTop: $('body').height() }, 100);
        return false;
      });
    });



  </script>
</body>

</html>

meetapp/templates/meetapp/comment_confirm_delete.html
<form action="" method="post">
    {% csrf_token %}
    
    정말 삭제하시겠습니까?
    
    <input type="submit" value="삭제"/>
</form>

meetapp/templates/meetapp/comment_declaration.html
{% extends 'meetapp/base.html' %}
{% block content %}
{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'css/comment_declaration.css' %}" />
</head>

<section id="main">
    <form method="POST" enctype="multipart/form-data">
        <div class="title">
            <h1>신고 사유</h1>
        </div>
    {% csrf_token %}
    <div class="form_message">
        {{ form.message }}
    </div>
    <br>
    <div class="d-grid gap-2 col-5 mx-auto">
        <button class="btn btn-outline-secondary" type="submit">접수</button>
    </div>
    </form>
</section>
{% endblock content %}

meetapp/templates/meetapp/post_detail.html
{% extends 'meetapp/base.html' %} {% block content %} {% load static %} <br />
<html>
<title>{{post.title}} - ConcertMeet</title>

<head>
    <link rel="stylesheet" href="{% static 'css/post_detail.css' %}" />
    <script src="{% static 'js/likes.js' %}"></script>
</head>

<body>
    <section class="det_container">
        <section id="title">
            <h2>{{ post.title }}</h2><br>

            <div class="user_and_pcp">
                <p>
                    #{{ post.category }}
                    |
                    <span id="pcp_user_cnt" value="{{ post.pcp.pcp_user_count }}">{{ post.pcp.pcp_user_count }}</span>
                    /
                    <span id="pcp_total_cnt" value="{{ post.pcp.pcp_user_total }}">{{ post.pcp.pcp_user_total }}</span>
                    명
                    <br>
                    <a href="{% url 'account:user' post.user.username %}">{{ post.user.name }}</a>
                </p>
            </div>
        </section>

        <section id="content">
            {{ post.content }}
        </section>

        <section id="edit">
            <div class="manage">
                {% if post.user.username == request.user.username %}
                <a href="{% url 'meetapp:post_edit' post.id %}"><button class="btn btn-dark">수정</button></a>
                <a href="{% url 'meetapp:post_delete' post.id %}"><button class="btn btn-dark">삭제</button></a>
                {% else %}
                <a>
                    <button class="like" name="{{ post.id }}" onclick="onClick()">
                        <span class="fa fa-heart"></span>
                    </button>
                </a>
                {% if is_pcp %}
                <a href="{% url 'account:review_new' post.user.username %}"><button class="btn btn-dark">후기
                        작성</button></a>
                {% endif %}
                <a href="{% url 'meetapp:post_declaration' post.id %}"><button class="btn btn-dark">신고</button></a>
                {% endif %}
                <a href="{% url 'meetapp:post_list' %}"><button class="btn btn-dark">목록</button></a>
            </div>
        </section>

        <hr>

        <section id="comment"><br>
            <h4>댓글</h4><br>
            <form action="{% url 'meetapp:comment_new' post.id %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <textarea cols="40" rows="3" class="form-control" name="message" id="message"
                        value="{{ form.message.value|default_if_none:'' }}" placeholder="댓글로 참가 의사를 표현하세요"></textarea>
                </div><br>
                <div class="d-grid gap-2 d-sm-flex justify-content-sm-end">
                    <input type="submit" class="btn btn-dark" value="작성">
                </div>
            </form>

            <ul>
                {% for comment in post.comment_set.all %}
                <li>
                    <div>
                        {% if comment.user.username == request.user.username %}
                        <!-- <a href="{{ comment.get_edit_url }}">
                            <button class="btn btn-dark">수정</button>
                        </a> -->
                        <a>
                            <input type="hidden" id="delete_url" name="delete_url" value="{{ comment.get_delete_url }}">
                            <button onclick="deletecmtfunc();" class="btn btn-dark">삭제</button>
                        </a>
                        {% endif %}
                        {% if request.user.username == post.user.username and comment.user.username != request.user.username %}
                        <a>
                            <input type="hidden" id="pcp_url" name="pcp_url"
                                value="{% url 'meetapp:pcp_add' post.id comment.id %}">
                            <input type="hidden" id="del_pcp_url" name="del_pcp_url"
                                value="{% url 'meetapp:pcp_delete' post.id comment.id %}">
                            <button id="pcp_btn" onclick="addpcpfunc();" class="btn btn-dark">참가자 추가</button>
                            <button id="del_pcp_btn" onclick="delpcpfunc();" class="btn btn-dark">참가자 삭제</button>
                        </a>
                        {% endif %}
                        {% if comment.user.username != request.user.username %}
                        <a href="{% url 'meetapp:comment_declaration' post.id comment.id %}"><input type="button"
                                class="btn btn-dark" value='신고'></a>
                        {% endif %}
                    </div>
                    <div class="cmt_tit">
                        {{ comment.user.name }} | {{ comment.created_at }} <br>
                    </div>
                    <div class="cmt_msg">
                        {{ comment.message }}
                    </div>

                </li>
                {% endfor %}
            </ul>
        </section>
    </section>
</body>

</html>

<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script type="text/javascript">
    $(".like").click(function () {
        var pk = $(this).attr("name");
        $.ajax({
            type: "POST",
            url: "{% url 'meetapp:post_like' %}",
            data: { pk: pk, csrfmiddlewaretoken: "{{ csrf_token }}" },
            dataType: "json",
            success: function (response) {
                $("#count-" + pk).html(response.likes_count);
            },
            error: function (request, status, error) {
                alert("로그인이 필요합니다.");
                window.location.replace("/user/login/");
            },
        });
    });
    function deletefunc() {
        if (confirm('정말 삭제하시겠습니까?'))
            window.location = document.getElementById("del_post_url").value;
    }

    // $(".cmt_edit").click(function () {
    //     var cid = $(this).attr("name");
    //     var form_str = '<form action="{{ comment.get_edit_url }}" method="POST">{% csrf_token %}<textarea cols="40" rows="3" class="form-control" name="message" id="message" value="{{ comment.message|linebreaks }}"></textarea></form>';
    //     $(".cmt_edit_msg_" + cid).html(form_str);
    // });

    function deletecmtfunc() {
        if (confirm('정말 삭제하시겠습니까?'))
            window.location = document.getElementById("delete_url").value;
    }

    function addpcpfunc() {

        if (confirm('해당 사용자를 추가하시겠습니까?')) {
            var cur = document.getElementById("pcp_user_cnt").value;
            console.log(cur)
            var tot = document.getElementById("pcp_total_cnt").value;
            console.log(tot)
            if (tot - cur == 0)
                alert("최대인원을 초과하여 추가할 수 없습니다.");
            else {
                $.ajax({
                    type: "POST",
                    url: document.getElementById("pcp_url").value,
                    data: { 'csrfmiddlewaretoken': '{{ csrf_token }}' },
                    dataType: "json",
                    success: function (response) {
                        alert("성공적으로 추가되었습니다.");
                        $("#pcp_user_cnt").text(response.pcp_user_count);
                    },
                    error: function (request, status, error) {
                        if (status == 0)
                            alert("이미 등록된 사용자입니다.");
                        else
                            alert("추가에 실패하였습니다.");
                    },
                });
            }
        }
    }
    function delpcpfunc() {
        if (confirm('해당 사용자를 제외하시겠습니까?')) {
            $.ajax({
                type: "POST",
                url: document.getElementById("del_pcp_url").value,
                data: { 'csrfmiddlewaretoken': '{{ csrf_token }}' },
                dataType: "json",
                success: function (response) {
                    alert("성공적으로 삭제되었습니다.");
                    $("#pcp_user_cnt").text(response.pcp_user_count);
                },
                error: function (request, status, error) {
                    if (status == 0)
                        alert("참가하지 않은 사용자입니다.");
                    else
                        alert("삭제에 실패하였습니다.");
                },
            });
        }
    }
</script>
{% endblock content %}